FROM node:16-slim

RUN echo "_cache check_"
# Set the working directory.
WORKDIR /usr/src/app

# Copy the file from your host to yout current location
ADD package.json package.json
ADD Api.js .

# Run the command inside your image filesystem.
RUN npm install

# Run the specified command within the container
CMD ["node", "Api.js"]