apiVersion: batch/v1
kind: CronJob
metadata:
  name: alarmbot
spec:
  schedule: "*/1 * * * *"
  startingDeadlineSeconds: 60
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: alarmbot
            image: leedowon/goormalarm:1.1
            imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure