apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: alarmbot
spec:
  schedule: "*/1 * * * *"
  startingDeadlineSeconds: 60
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: alarmbot
            image: 562282606062.dkr.ecr.ap-northeast-2.amazonaws.com/goorm/telegram-alarm:1.0
            imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure